# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsDev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Hex'
pod 'DKImagePickerController'
pod 'IQKeyboardManagerSwift'
pod 'SKPhotoBrowser'
pod 'Kingfisher'
pod 'NVActivityIndicatorView'
pod 'Hero'
pod 'SkyFloatingLabelTextField'
pod 'FontAwesome.swift'
pod 'ExpandableLabel'

  # Pods for LetsDev

end
